version: '3'
volumes:
 portainer_data:
services:
 jupyter:
  image: chiaraforresi/bdp2-mid-term_review
  ports: 
   - 8888:8888
  volumes:
   - $PWD/work:/home/jovyan/work
 
 portainer:
  image: portainer/portainer
  ports:
    - 9000:9000
  restart: always
  volumes:
   - portainer_data:/data
   - /var/run/docker.sock:/var/run/docker.sock
